### ISSUE TITLE
paiza回答コード掲載停止のお願い

### ISSUE THREAD

**Issue by paiza-team** [smallclover/Paiza#1]
いつもご利用ありがとうございます。
paiza運営事務局です。

貴殿のgithubページ「 https://github.com/smallclover/Paiza 」を拝見しまして、
paizaの掲載中の問題について記載されてらっしゃったため、ご連絡させていただきました。

paizaにおいては、利用規約第8条（禁止事項）10項で、問題に関する内容、解答、ヒントを含め、
他サイトでの掲載を禁止させていただいております。

利用規約第8条10項（禁止事項）
http://paiza.jp/guide/kiyaku

＝＝＝
10.ブログ・SNS等本サイト以外の媒体（インターネット媒体に限られず、不特定多数が閲覧可能なものを全て含む。）上において、
当社が出題した問題の内容、当該問題に対する解答、解答へのヒント等の示唆及びカンニング等の不正を助長する内容等を掲載する行為.。
＝＝＝

現在ご掲載中のコードついて、早急に削除または非掲載対応をお願いできますでしょうか。

大変お手数ですが、よろしくお願い致します。

**Comment by smallclover** [comment]
承知いたしました。今週末まで、削除します。
